### PR TITLE
(doc) Fix wrong filename (schema/facter.yaml vs. schema/facter.json)

### PR DESCRIPTION
**Pull request by mattthias**
Hi, 

the CONTRIBUTING.md mentioned a file named `schema/facter.json` but the file is named `schema/facter.yaml`. 

Best wishes,
Matthias

### CODE REVIEW

**Comment by kylog** [comment]
Good catch, thanks! It's actually `lib/schema/facter.yaml` - can you update for that path?

**Comment by peterhuene** [comment]
Hi @mattthias, could you squash these two commits together and then force push to your branch?  I'll then merge it in.

**Comment by mattthias** [comment]
HI @peterhuene, i squashed the two commits together.

best wishes,
Matthias

**Comment by peterhuene** [comment]
@mattthias Thanks again for the contribution!

**Pull request merged**
