### PR TITLE
(CFACT-209) Update build docs for Windows

### PR DESCRIPTION
**Pull request by MikaelSmith**
Removes multiple sources of build documentation for Windows, and
provides links for Chocolatey packages where appropriate.

Specific MinGW-w64 settings are removed from the README to avoid
packaging issues; the packaging configuration contains more details.

### CODE REVIEW

**Comment by ferventcoder** [comment]
Looks good, does it loose specific commands one may want to pass to install those tools?

**Comment by MikaelSmith** [comment]
It should work with the defaults. That may change in the future, in which case looking at https://github.com/puppetlabs/cfacter/blob/master/contrib/cfacter.ps1 or its future replacement will give more specific instructions.

**Comment by MikaelSmith** [comment]
Ok, maybe not strictly true. The defaults don't work for Windows Server 2003.

**Comment by MikaelSmith** [comment]
I'll play around with specific command-line instructions.

**Comment by MikaelSmith** [comment]
Added some options. My preference would be to keep it simpler, and leave the specifics up to actual packaging scripts. We don't support older OS versions for the other instructions, something that's only needed by Server 2003 also isn't a high priority.

I also don't like having a redundant setup script; it's another (rather complicated) thing to keep correct and up-to-date.

**Comment by ferventcoder** [comment]
:)

**Comment by ferventcoder** [comment]
LGTM

**Pull request merged**
