### PR TITLE
(CFACT-202) Run tests on Windows build

### PR DESCRIPTION
**Pull request by MikaelSmith**
Runs unit tests and the cfacter executable when build completes.

### CODE REVIEW

**Comment by peterhuene** [comment]
Perhaps we should just do `add_test(NAME "cfacter" COMMAND cfacter)` so that ctest always executes cfacter?  Although I don't know how to suppress output :/

**Comment by MikaelSmith** [comment]
I can play with that.

**Comment by MikaelSmith** [comment]
Pretty sure it suppresses output by default.

On Wed, Feb 11, 2015 at 3:39 PM, Michael Smith <michael.smith@puppetlabs.com

**Comment by peterhuene** [comment]
Will merge when CI is green.

**Pull request merged**
