### PR TITLE
(CFACT-205) Build CFacter for Fedora 20

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by melissa** [comment]
```
[root@u10kw390mmaig3z ~]# yum install cfacter
Resolving Dependencies
--> Running transaction check
---> Package cfacter.i386 0:0.2.0.385-1.fc20 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

============================================================================================================================================================================
 Package                     Arch                     Version                                 Repository                                                               Size
============================================================================================================================================================================
Installing:
 cfacter                     i386                     0.2.0.385-1.fc20                        pl-cfacter-de9dad2097ab93e93552f8a92d89329882eb4168                     1.1 M

Transaction Summary
============================================================================================================================================================================
Install  1 Package

Total download size: 1.1 M
Installed size: 4.6 M
Is this ok [y/d/N]: y
Downloading packages:
cfacter-0.2.0.385-1.fc20.i386.rpm                                                                                                                    | 1.1 MB  00:00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : cfacter-0.2.0.385-1.fc20.i386                                                                                                                            1/1
  Verifying  : cfacter-0.2.0.385-1.fc20.i386                                                                                                                            1/1

Installed:
  cfacter.i386 0:0.2.0.385-1.fc20

Complete!
[root@u10kw390mmaig3z ~]# cfacter
cfacterversion => 0.2.0
disks => {
  sda => {
    model => "Virtual disk",
    size => "8.00 GiB",
    size_bytes => 8589934592,
    vendor => "VMware"
  },
  sr0 => {
    model => "VMware IDE CDR10",
    size => "1.00 GiB",
    size_bytes => 1073741312,
    vendor => "NECVMWar"
  }
}
dmi => {
  bios => {
    release_date => "07/30/2013",
    vendor => "Phoenix Technologies LTD",
    version => "6.00"
  },
  board => {
    manufacturer => "Intel Corporation",
    product => "440BX Desktop Reference Platform",
    serial_number => "None"
  },
  chassis => {
    asset_tag => "No Asset Tag",
    type => "Other"
  },
  manufacturer => "VMware, Inc.",
  product => {
    name => "VMware Virtual Platform",
    serial_number => "VMware-42 0f 4e 5d ae 7d 14 a7-51 f3 ca 3a bf ef 04 1c",
    uuid => "420F4E5D-AE7D-14A7-51F3-CA3ABFEF041C"
  }
}
facterversion => 0.2.0
filesystems => ext2,ext3,ext4
identity => {
  gid => 0,
  group => "root",
  uid => 0,
  user => "root"
}
is_virtual => true
kernel => Linux
kernelmajversion => 3.11
kernelrelease => 3.11.10-301.fc20.i686+PAE
kernelversion => 3.11.10
memory => {
  swap => {
    available => "820.00 MiB",
    available_bytes => 859828224,
    capacity => "0%",
    total => "820.00 MiB",
    total_bytes => 859828224,
    used => "0 bytes",
    used_bytes => 0
  },
  system => {
    available => "1.88 GiB",
    available_bytes => 2021281792,
    capacity => "4.43%",
    total => "1.97 GiB",
    total_bytes => 2114998272,
    used => "89.38 MiB",
    used_bytes => 93716480
  }
}
mountpoints => {
  / => {
    available => "1.62 GiB",
    available_bytes => 1739816960,
    capacity => "34.58%",
    device => "/dev/mapper/fedora-root",
    filesystem => "ext4",
    options => [
      "rw",
      "seclabel",
      "relatime",
      "data=ordered"
    ],
    size => "2.48 GiB",
    size_bytes => 2659336192,
    used => "876.92 MiB",
    used_bytes => 919519232
  },
  /boot => {
    available => "411.60 MiB",
    available_bytes => 431592448,
    capacity => "13.57%",
    device => "/dev/sda1",
    filesystem => "ext4",
    options => [
      "rw",
      "seclabel",
      "relatime",
      "data=ordered"
    ],
    size => "476.22 MiB",
    size_bytes => 499355648,
    used => "64.62 MiB",
    used_bytes => 67763200
  }
}
networking => {
  dhcp => "10.32.44.11",
  domain => "delivery.puppetlabs.net",
  fqdn => "u10kw390mmaig3z",
  hostname => "u10kw390mmaig3z",
  interfaces => {
    ens192 => {
      dhcp => "10.32.44.11",
      ip => "10.32.115.111",
      ip6 => "fe80::250:56ff:fe8f:38d0",
      mac => "00:50:56:8f:38:d0",
      mtu => 1500,
      netmask => "255.255.240.0",
      netmask6 => "ffff:ffff:ffff:ffff::",
      network => "10.32.112.0",
      network6 => "fe80::"
    },
    lo => {
      ip => "127.0.0.1",
      ip6 => "::1",
      mtu => 65536,
      netmask => "255.0.0.0",
      netmask6 => "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
      network => "127.0.0.0",
      network6 => "::1"
    }
  },
  ip => "10.32.115.111",
  ip6 => "fe80::250:56ff:fe8f:38d0",
  mac => "00:50:56:8f:38:d0",
  mtu => 1500,
  netmask => "255.255.240.0",
  netmask6 => "ffff:ffff:ffff:ffff::",
  network => "10.32.112.0",
  network6 => "fe80::"
}
os => {
  architecture => "i686",
  family => "RedHat",
  hardware => "i386",
  name => "Fedora",
  release => {
    full => "20",
    major => "20"
  }
}
path => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
processors => {
  count => 2,
  isa => "i686",
  models => [
    "Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz",
    "Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz"
  ],
  physicalcount => 2
}
ruby => {
  platform => "i386-linux",
  sitedir => "/usr/local/share/ruby/site_ruby/",
  version => "2.0.0"
}
selinux => true
selinux_config_mode => enforcing
selinux_current_mode => enforcing
selinux_enforced => true
selinux_policyversion => 28
ssh => {
  ecdsa => {
    key => "AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPcV0/oUuPzpvh9MYLDjh2dN2L7TxDT5qnzkOfSFFFkje0mMLgxqa/kjcHBkWTttt5Bos/szOnfV0EpjokiUZ78="
  },
  rsa => {
    key => "AAAAB3NzaC1yc2EAAAADAQABAAABAQDGNKagGRt7/fVLkGPjk4MVsVvCw8/fNcm67/IOYb3DeBHU/2+JY71Ch7KchNA9jg6sGA6IYRnZmLIuBNbPBNoIHQ+gCq/9P9MvvOpseRyf+jqtG8WI7hgnu5OOYlYdfmZE6mFaVIybeaqdqy2gkKDctIm0h11uzmWgCNQ3CxoBGcnZgq/aLfmgf1Ekoj6HEHEeOIFwhKFdjlI+R2BKTUjTd4q8/uKyQXGngPJa2BpAPRFCU/K/YHl98gtnTQlviaEcSVqrulgaWo0FVtdq4TFjPA0ICQfRRKmCGY8Vfrpg1YDBftujIeYgh7I1PKS9x6+0HwMU4BFPOAkqqiDvTGxL"
  }
}
system_uptime => {
  days => 0,
  hours => 15,
  seconds => 54089,
  uptime => "15:01 hours"
}
timezone => PST
virtual => vmware
[root@u10kw390mmaig3z ~]# which cfacter
/usr/bin/cfacter
[root@u10kw390mmaig3z ~]# ldd /usr/bin/cfacter
	linux-gate.so.1 =>  (0xb76e7000)
	libfacter.so.0.2.0 => /usr/lib/libfacter.so.0.2.0 (0xb73d7000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0xb73bc000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0xb73b7000)
	librt.so.1 => /usr/lib/librt.so.1 (0xb73ae000)
	libm.so.6 => /usr/lib/libm.so.6 (0xb7366000)
	libc.so.6 => /usr/lib/libc.so.6 (0xb71a8000)
	/lib/ld-linux.so.2 (0xb76e8000)
[root@u10kw390mmaig3z ~]# ldd /usr/lib/l
Display all 459 possibilities? (y or n)
[root@u10kw390mmaig3z ~]# ldd /usr/lib/libfacter.so
	linux-gate.so.1 =>  (0xb7720000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0xb73f5000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0xb73f0000)
	librt.so.1 => /usr/lib/librt.so.1 (0xb73e7000)
	libm.so.6 => /usr/lib/libm.so.6 (0xb73a0000)
	libc.so.6 => /usr/lib/libc.so.6 (0xb71e1000)
	/lib/ld-linux.so.2 (0xb7721000)
```

**Comment by melissa** [comment]
```
[root@x56kaomlvgbv516 ~]# yum install cfacter
Resolving Dependencies
--> Running transaction check
---> Package cfacter.x86_64 0:0.2.0.385-1.fc20 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

============================================================================================================================================================================
 Package                     Arch                       Version                               Repository                                                               Size
============================================================================================================================================================================
Installing:
 cfacter                     x86_64                     0.2.0.385-1.fc20                      pl-cfacter-de9dad2097ab93e93552f8a92d89329882eb4168                     1.1 M

Transaction Summary
============================================================================================================================================================================
Install  1 Package

Total download size: 1.1 M
Installed size: 4.9 M
Is this ok [y/d/N]: y
Downloading packages:
cfacter-0.2.0.385-1.fc20.x86_64.rpm                                                                                                                  | 1.1 MB  00:00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : cfacter-0.2.0.385-1.fc20.x86_64                                                                                                                          1/1
  Verifying  : cfacter-0.2.0.385-1.fc20.x86_64                                                                                                                          1/1

Installed:
  cfacter.x86_64 0:0.2.0.385-1.fc20

Complete!
[root@x56kaomlvgbv516 ~]# cfacter
cfacterversion => 0.2.0
disks => {
  sda => {
    model => "Virtual disk",
    size => "8.00 GiB",
    size_bytes => 8589934592,
    vendor => "VMware"
  },
  sr0 => {
    model => "VMware IDE CDR10",
    size => "1.00 GiB",
    size_bytes => 1073741312,
    vendor => "NECVMWar"
  }
}
dmi => {
  bios => {
    release_date => "07/30/2013",
    vendor => "Phoenix Technologies LTD",
    version => "6.00"
  },
  board => {
    manufacturer => "Intel Corporation",
    product => "440BX Desktop Reference Platform",
    serial_number => "None"
  },
  chassis => {
    asset_tag => "No Asset Tag",
    type => "Other"
  },
  manufacturer => "VMware, Inc.",
  product => {
    name => "VMware Virtual Platform",
    serial_number => "VMware-42 0f b0 5c bc 96 09 c8-de f3 e6 b6 43 61 12 5e",
    uuid => "420FB05C-BC96-09C8-DEF3-E6B64361125E"
  }
}
facterversion => 0.2.0
filesystems => ext2,ext3,ext4
identity => {
  gid => 0,
  group => "root",
  uid => 0,
  user => "root"
}
is_virtual => true
kernel => Linux
kernelmajversion => 3.11
kernelrelease => 3.11.10-301.fc20.x86_64
kernelversion => 3.11.10
memory => {
  swap => {
    available => "820.00 MiB",
    available_bytes => 859828224,
    capacity => "0%",
    total => "820.00 MiB",
    total_bytes => 859828224,
    used => "0 bytes",
    used_bytes => 0
  },
  system => {
    available => "3.71 GiB",
    available_bytes => 3982974976,
    capacity => "3.96%",
    total => "3.86 GiB",
    total_bytes => 4147032064,
    used => "156.46 MiB",
    used_bytes => 164057088
  }
}
mountpoints => {
  / => {
    available => "5.57 GiB",
    available_bytes => 5975777280,
    capacity => "14.07%",
    device => "/dev/mapper/fedora-root",
    filesystem => "ext4",
    options => [
      "rw",
      "seclabel",
      "relatime",
      "data=ordered"
    ],
    size => "6.48 GiB",
    size_bytes => 6954303488,
    used => "933.20 MiB",
    used_bytes => 978526208
  },
  /boot => {
    available => "410.22 MiB",
    available_bytes => 430151680,
    capacity => "13.86%",
    device => "/dev/sda1",
    filesystem => "ext4",
    options => [
      "rw",
      "seclabel",
      "relatime",
      "data=ordered"
    ],
    size => "476.22 MiB",
    size_bytes => 499355648,
    used => "66.00 MiB",
    used_bytes => 69203968
  }
}
networking => {
  dhcp => "10.32.44.11",
  domain => "delivery.puppetlabs.net",
  fqdn => "x56kaomlvgbv516",
  hostname => "x56kaomlvgbv516",
  interfaces => {
    ens192 => {
      dhcp => "10.32.44.11",
      ip => "10.32.113.185",
      ip6 => "fe80::250:56ff:fe8f:dab3",
      mac => "00:50:56:8f:da:b3",
      mtu => 1500,
      netmask => "255.255.240.0",
      netmask6 => "ffff:ffff:ffff:ffff::",
      network => "10.32.112.0",
      network6 => "fe80::"
    },
    lo => {
      ip => "127.0.0.1",
      ip6 => "::1",
      mtu => 65536,
      netmask => "255.0.0.0",
      netmask6 => "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
      network => "127.0.0.0",
      network6 => "::1"
    }
  },
  ip => "10.32.113.185",
  ip6 => "fe80::250:56ff:fe8f:dab3",
  mac => "00:50:56:8f:da:b3",
  mtu => 1500,
  netmask => "255.255.240.0",
  netmask6 => "ffff:ffff:ffff:ffff::",
  network => "10.32.112.0",
  network6 => "fe80::"
}
os => {
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "Fedora",
  release => {
    full => "20",
    major => "20"
  }
}
path => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
processors => {
  count => 2,
  isa => "x86_64",
  models => [
    "Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz",
    "Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz"
  ],
  physicalcount => 2
}
ruby => {
  platform => "x86_64-linux",
  sitedir => "/usr/local/share/ruby/site_ruby/",
  version => "2.0.0"
}
selinux => true
selinux_config_mode => enforcing
selinux_current_mode => enforcing
selinux_enforced => true
selinux_policyversion => 28
ssh => {
  ecdsa => {
    key => "AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBC2kStTZTgmFC44N9N/is4VtHyI4I4VuzNI1Z1ejVlfp5/ko5YSqFAVcnIHjDUDpymsebXDVE5KFRgd/IjFxvws="
  },
  rsa => {
    key => "AAAAB3NzaC1yc2EAAAADAQABAAABAQC0LI29oV3nPDefAKusinDG90DL4rzzxXaxky6DeL/9nYFJ40SP5IiQ5FX7nQ2xYHBU0NdNMT6oPRB91xfZ5aV0QyUC81oena43YM0uGppEK/kZ7X+2NUoycrMjaqu33FnEo+FWjEEz5aQJSc6/9ZW8wt9NsSejfmwt29Qw41c+Qef9G2JjvbRzPaQ6TZWCZnQUnTlsxLpgCymXnbJPXLQPWF9rUNBrzZxpD86qgaQqZxRMfndp/o4UN4atQbJGvlLxs8Umg/+GaXn2B/f2ER06L8swcnhs+HLHQt4Kz+gTE8YpVszh36xeShYY/ZiOkF/V69vtxKk8TGFHQUrgFnWt"
  }
}
system_uptime => {
  days => 0,
  hours => 14,
  seconds => 51189,
  uptime => "14:13 hours"
}
timezone => PST
virtual => vmware
[root@x56kaomlvgbv516 ~]# which cfacter
/usr/bin/cfacter
[root@x56kaomlvgbv516 ~]# ldd /usr/bin/cfacter
	linux-vdso.so.1 =>  (0x00007fff8279f000)
	libfacter.so.0.2.0 => /usr/lib/libfacter.so.0.2.0 (0x00007f0f2150a000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f0f212e7000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f0f210e3000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f0f20edb000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f0f20bd3000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f0f20814000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0f21a63000)
[root@x56kaomlvgbv516 ~]# ldd /usr/lib/libfacter.so
	linux-vdso.so.1 =>  (0x00007fff683e6000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f02f56d8000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f02f54d3000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f02f52cb000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f02f4fc4000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f02f4c04000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f02f5e53000)
```

**Comment by melissa** [comment]
http://builds.puppetlabs.lan/cfacter/de9dad2097ab93e93552f8a92d89329882eb4168/

**Comment by MikaelSmith** [comment]
:+1:

**Pull request merged**
