### PR TITLE
(CFACT-223) Replace gmock framework with Catch.

### PR DESCRIPTION
**Pull request by peterhuene**
Replacing the gmock framework with Catch for unit tests.
Catch has the benefit of BDD style tests as well as a more sane test
setup/tear down pattern.

Removing all of gmock from the build and replacing with the single Catch
header file.

### CODE REVIEW

**Comment by peterhuene** [comment]
Doesn't look like unity is happy with Catch.  I'll look into the failure tomorrow (everything passes on Windows without a unity build, though).

**Comment by MikaelSmith** [comment]
This might be easier to diff if removing gmock were a different commit.

**Comment by peterhuene** [comment]
I'll split them apart.  As for the unity problem, I'm going to disable unity for only the test executable and see how that goes in terms of build time.

**Comment by peterhuene** [comment]
I've split the commit apart and added a new one to see if we can get AppVeyor passing for now.

**Comment by peterhuene** [comment]
@MikaelSmith Okay, AppVeyor is now happy.

**Comment by MikaelSmith** [comment]
Overall this approach looks good. If Coveralls comes back and says code coverage hasn't changed, I'll take that as evidence that all the tests are still there.

It looks like you re-organized a bit; I'm not sure it's worth the time to go test-by-test and make sure they're all still there. I'll take your word for it.

**Comment by MikaelSmith** [comment]
:+1:

**Comment by peterhuene** [comment]
@MikaelSmith Yeah, the coverage should actually increase a little bit.  I added a few more scenarios than we tested before where I saw they were missing.

**Pull request merged**
