### PR TITLE
(CFACT-219) Fix executing external ruby fact

### PR DESCRIPTION
**Pull request by MikaelSmith**
A Ruby script can be used as an external fact. On Windows, that doesn't
work if you try to invoke the script using CreateProcess; an execution
environment that knows about Ruby is required. Wraps external facts in a
shell to ensure scripts are run in a usable environment.

### CODE REVIEW

**Comment by peterhuene** [comment]
Looks like AppVeyor timed out for some reason.

**Comment by MikaelSmith** [comment]
I'm not sure why that's occuring.

**Comment by Iristyle** [comment]
Functional :+1: 

With an external Ruby fact in `c:\ProgramData\PuppetLabs\facter\facts.d\ruby_version.rb`:

```ruby
puts "ext_rbver=#{RUBY_VERSION}"
```

With the cfacter executable prior to this set of changes:

```
2015-02-12 08:28:56.658255 DEBUG puppetlabs.facter - resolving facts from executable file "C:/ProgramData\PuppetLabs\facter\facts.d\ruby_version.rb".
2015-02-12 08:28:56.658255 DEBUG puppetlabs.facter - executing command: C:/ProgramData\PuppetLabs\facter\facts.d\ruby_version.rb
2015-02-12 08:28:56.658255 ERROR puppetlabs.facter - error while processing "C:/ProgramData\PuppetLabs\facter\facts.d\ruby_version.rb" for external facts: child process failed to start
```

With the cfacter executable that @MikaelSmith provided that incorporates these changes:

```
C:\Program Files\Puppet Labs\Puppet\bin>cfacter ext_rbver
2.1.5
```

**Comment by MikaelSmith** [comment]
For some reason the unit tests seem to cause havoc on AppVeyor, trying out changes to avoid that.

**Pull request merged**
