### PR TITLE
(CFACT-210) build cfacter for fedora 21

### PR DESCRIPTION
**Pull request by heathseals**
http://builds.delivery.puppetlabs.net/cfacter/1549f785b6a5194976851ca459f07d6f10c57c33/

cfacter on fedora-21-i386
```
[root@ecr00pmcp7bh15f yum.repos.d]# cfacter os
{
  architecture => "i686",
  family => "RedHat",
  hardware => "i386",
  name => "Fedora",
  release => {
    full => "21",
    major => "21"
  }
}
[root@ecr00pmcp7bh15f yum.repos.d]#
```

cfacter on fedora-21-x86_64
```
[root@smgpgjk80b5jqbt yum.repos.d]# cfacter os
{
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "Fedora",
  release => {
    full => "21",
    major => "21"
  }
}
[root@smgpgjk80b5jqbt yum.repos.d]#
```

### CODE REVIEW

**Comment by haus** [comment]
@heathseals can you amend the commit message to something slightly more concrete, like "(RE-3775) Add fedora 21 to mocks list in build_defaults.yaml" or something?

**Comment by melissa** [comment]
@heathseals also, I should have done this earlier, but since this is getting into the cfacter repo, this should be referencing a cfacter ticket. I've moved the RE ticket to be CFACT-210

**Comment by MikaelSmith** [comment]
So the commit message should be updated to refer to CFACT-210?

**Comment by melissa** [comment]
@MikaelSmith yes

**Comment by melissa** [comment]
:+1:

**Pull request merged**
