### PR TITLE
(CFACT-269) Update external search path to use new AIO path

### PR DESCRIPTION
**Pull request by kylog**

### CODE REVIEW

**Comment by peterhuene** [comment]
I assume we don't want to configure PR CI for this?

**Comment by kylog** [comment]
Ah yes, good q. I'm assuming the same, because this is so limited and because we don't intend to do any more fixup to cfacter 0.4.0.

Once this is in, we can do a super lightweight process to get this into puppet-agent builds:
* update the version to 0.4.1
* tag it as 0.4.1
* PR puppet-agent to build off that tag

**Comment by MikaelSmith** [comment]
:+1:

**Comment by MikaelSmith** [comment]
Oh yeah, looks like we disabled Travis and AppVeyor on this repo. I'll manually smoke test.

**Comment by MikaelSmith** [comment]
Found my custom fact in `~/.puppetlabs/opt/facter/facts.d`.

**Pull request merged**
