### PR TITLE
(CFACT-154) Add a facter schema and unit tests to verify the schema.

### PR DESCRIPTION
**Pull request by peterhuene**
Adding lib/schema/facter.yaml as the schema for libfacter output.

This file also serves as a place to extract fact documentation from.

Adding three unit tests:
  - Test that the schema file itself is valid.
  - Test that outputting every fact conforms to the schema.
  - Test that outputting the current platform's facts conforms to the
    schema.

Also included is some refactoring to a few resolvers that were missing "base" resolver types.  This was necessary to make the schema unit test less brittle (i.e. it didn't have to manually add facts to the test collection).

As part of the schema work, a few inconsistencies with the Facter 2.x were also fixed.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Woo, Windows crash.

**Comment by peterhuene** [comment]
Looks like I forgot the selinux facts in the schema.  Huzzah to schema validation.

**Comment by peterhuene** [comment]
@kylog Currently this doesn't do any value validation, but we could add something like that if so desired.  Could add in a `value_pattern` attribute that does a regex against the value.

**Comment by peterhuene** [comment]
@kylog I'll add value validation to this PR.  Changing back to WIP.

**Comment by peterhuene** [comment]
@kylog I've added types for "ip", "ip6", and "mac" to validate the networking fact values.

**Comment by MikaelSmith** [comment]
Have you done a run of this on Solaris?

**Comment by MikaelSmith** [comment]
General comment on the zfs/zpool refactoring: ZFS isn't limited to Solaris, but we're not querying it elsewhere. Maybe the naming for facts shouldn't be Solaris specific?

**Comment by peterhuene** [comment]
re: ZFS/zpool facts: they aren't Solaris specific in naming and the "base" ZFS/zpool resolvers are meant to be platform agnostic in case we add ZFS facts for other platforms.  Which in particular would you like changed?

**Comment by peterhuene** [comment]
I'll get the changes tested properly on Solaris before we merge this.  Clearly the typo in the zpool resolver would not have built.

**Comment by MikaelSmith** [comment]
Finished a first-pass through.

**Comment by peterhuene** [comment]
Cool, will ping you when I've pushed up the fixes.

**Comment by peterhuene** [comment]
@MikaelSmith Pushed up fixes and added a commit for Windows 2003 notes.  Testing things out on Solaris.

**Comment by MikaelSmith** [comment]
:+1: pending CI and fixes/verification on Solaris.

**Comment by peterhuene** [comment]
@MikaelSmith On Solaris 11 I verified the new `solaris_zones` structured fact, the ZFS/zpool facts still resolve correct, and unit tests pass.  Once CI is happy, we're good to go.

**Pull request merged**
