### PR TITLE
(maint) Choco improvements

### PR DESCRIPTION
**Pull request by ferventcoder**
Provide debugging output from Chocolatey, so when things go wrong, it is easier
to determine why that is the case e.g. not finding packages.

Move the default set of args passed to all choco commands to an array to reduce change and DRY things up a bit.

### CODE REVIEW

**Comment by ferventcoder** [comment]
@MikaelSmith here you go.

**Comment by ferventcoder** [comment]
I started to work on a default set of options we can pass to chocolatey so we can just adjust there and avoid updating all of these.

**Comment by MikaelSmith** [comment]
Thanks. I have a few changes I'm making, I'll roll these into it.

**Comment by ferventcoder** [comment]
I have more for you as well.
Will push for your viewing enjoyment.

**Comment by ferventcoder** [comment]
@MikaelSmith There you go, default set of args

**Pull request merged**
